CREATE TABLE SYSTEMUSERS
(
	SU_ID INT PRIMARY KEY,
    SU_LOGINNAME VARCHAR(100),
    SU_PASSWORD VARCHAR(500)
);

CREATE TABLE YOUNGS
(
	YOU_ID INT PRIMARY KEY,
    YOU_NAME VARCHAR(100),
    YOU_MAIL VARCHAR(100),
    YOU_DATEBIRHTDAY VARCHAR(45),
	YOU_PHONE VARCHAR(45),
    YOU_INSTAGRAM VARCHAR(100),
    YOU_GENRE VARCHAR(45),
    YOU_STATUS CHAR(1)
);

CREATE TABLE YOUNGS_ADDRESS
(
	YADD_ID INT PRIMARY KEY,
    YOU_ID INT,
    YADD_STREET VARCHAR(100),
    YADD_NEIGHBORHOOD VARCHAR(100),
    YADD_NUMBER VARCHAR(10),
    YADD_CITY VARCHAR(100),
    YADD_ZIPCODE VARCHAR(45),
    
    FOREIGN KEY (YOU_ID) REFERENCES YOUNGS (YOU_ID)
);

CREATE TABLE DEPARTAMENTS
(
	DP_ID INT PRIMARY KEY,
    DP_DESC VARCHAR(500),
    DP_STATUS CHAR(1)
);

CREATE TABLE YOUNGS_DEPARTAMENTS
(
	YDP_ID INT PRIMARY KEY,
    YOU_ID INT,
    DP_ID INT
);

/*ALTER TABLE YOUNGS_DEPARTAMENTS ADD FOREIGN KEY (YOU_ID) REFERENCES YOUNGS (YOU_ID)*/
/*ALTER TABLE YOUNGS_DEPARTAMENTS ADD FOREIGN KEY (DP_ID) REFERENCES DEPARTAMENTS (DP_ID)*/